### PR TITLE
Building trees with ska

### PR DESCRIPTION
**Pull request by tmaklin**
I totally intended to write this anyway regardless of the group retreat or not.

### CODE REVIEW

**Comment by johnlees** [comment]
>     * For gubbins, don't you need to use `ska map` rather than `ska align` as we need the output alignment in a meaningful order? (as a smaller point, this would also allow the use of `--ambig-mask` to turn the IUPAC codes to Ns automatically).

Although I think leaving `ska align + VeryFastTree` as the left panel would be good, and my suggestion would be to just using `ska map` for the right panel. This would demonstrate the other major mode it can be run in too

**Comment by tmaklin** [comment]
Thanks, good suggestions! I've mostly used this for building within-lineage trees but couldn't find a nice dataset that has the assemblies available somewhere so the across species stuff is new to me.

> For gubbins, don't you need to use ska map rather than ska align as we need the output alignment in a meaningful order? (as a smaller point, this would also allow the use of --ambig-mask to turn the IUPAC codes to Ns automatically).
- Makes sense - I haven't used this for across-species workflows before so didn't know about ska map.

> We should add a note that gubbins isn't supposed to be run across a species (maybe link to quote the 'What type of dataset can be analysed with Gubbins?' on the gubbins doc page) but that it does the trick for a rough and ready removal to get overall topology.
- I'll make it more clear that gubbins is more suited for lineage analyses.
> This is semantic, but could we have this under guides rather than the blog? I'd like to get more tutorials under that section and this fits the bill neatly.
- Absolutely, didn't notice that there are more sections on the website.

> Although I think leaving ska align + VeryFastTree as the left panel would be good, and my suggestion would be to just using ska map for the right panel. This would demonstrate the other major mode it can be run in too
- Will do!

**Comment by tmaklin** [comment]
I think I'll change the second example to looking at variation within the largest SC because that makes more sense with gubbins.

**Comment by tmaklin** [comment]
Much better now, anything else?

**Comment by johnlees** [comment]
This is excellent!! Thanks

**Review by johnlees — APPROVED** [review]

**Pull request merged**
