### PR TITLE
add ggcaller installation doc

### PR DESCRIPTION
**Pull request by hsuehchien66**
add a blog of ggcaller installation from source and docker

### CODE REVIEW

**Comment by johnlees** [comment]
Something is wrong here, there shouldn’t be so many files changed. You might have committed the build folder. Can you use the git file history remover to clean this up? I can help if needed

**Comment by johnlees** [comment]
See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#using-the-bfg

**Comment by samhorsfield96** [comment]
ggCaller won’t work on macOS at the moment, so best to remove that bit from the guide for the time being.

**Comment by hsuehchien66** [comment]
> Something is wrong here, there shouldn’t be so many files changed. You might have committed the build folder. Can you use the git file history remover to clean this up? I can help if needed

I am afraid of making a mess. I will come to the office next week and ask someone in the group to do it properly

**Comment by johnlees** [comment]
Yep no worries, these things can be a bit complex! We can go through it next week

**Comment by johnlees** [comment]
This looks good thanks, I've fixed the commit on another branch and will merge there

**Pull request closed without merging**
